name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

defaults:
  run:
    shell: bash

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macOS-13", "windows-2022"]
        python-version: ["3.8", "3.12"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package & dependencies
      run: |
        pip --version
        pip install -e '.[test]' -U
        pip list

    - name: Tests
      run: pytest . -v
